# Generated by Django 4.1 on 2022-08-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_game_alter_invitation_player_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_game_player_combincation',
        ),
    ]
